# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish

on:
  release:
    types: [published]

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Github Releases To Discord
        uses: SethCohen/github-releases-to-discord@v1
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          color: "2105893"
          username: "rum"
          avatar_url: "https://raw.githubusercontent.com/sidan-lab/brand_assets/refs/heads/main/sidan_s_square.png"
          content: "Hey fellow Go Cardano devs! New version of [rum](https://github.com/sidan-lab/rum) has been published:"
          footer_title: "Changelog"
          reduce_headings: true
